---
title: "EIA data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EIA time series data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Finding the desired data

Like directory information, data is obtained based on a terminal directory path.
A complete example includes finding the ID for the series if you do not already know it.
Chances are you may already know the series IDs you need after using the API explorer on the EIA website.
Below, look for total electricity consumption.


```r
library(eia)
# eia_set_key("yourkey") # set API key if not already set globally
eia_dir()
```

```
## # A tibble: 14 × 3
##    id                name                            description                                                                                              
##    <chr>             <chr>                           <chr>                                                                                                    
##  1 coal              Coal                            EIA coal energy data                                                                                     
##  2 crude-oil-imports Crude Oil Imports               Crude oil imports by country to destination, includes type, grade, quantity.  Source: EIA-814  Interacti…
##  3 electricity       Electricity                     EIA electricity survey data                                                                              
##  4 international     International                   Country level production, consumption, imports, exports by energy source (petroleum, natural gas, electr…
##  5 natural-gas       Natural Gas                     EIA natural gas survey data                                                                              
##  6 nuclear-outages   Nuclear Outages                 EIA nuclear outages survey data                                                                          
##  7 petroleum         Petroleum                       EIA petroleum gas survey data                                                                            
##  8 seds              State Energy Data System (SEDS) Estimated production, consumption, price, and expenditure data for all energy sources by state and secto…
##  9 steo              Short Term Energy Outlook       Monthly short term (18 month) projections using STEO model.  Report and interactive projection data brow…
## 10 densified-biomass Densified Biomass               EIA densified biomass data                                                                               
## 11 total-energy      Total Energy                    These data represent the most recent comprehensive energy statistics integrated across all energy source…
## 12 aeo               Annual Energy Outlook           Annual U.S. projections using National Energy Modelling System (NEMS) for release year.  Report, documen…
## 13 ieo               International Energy Outlook    Annual international projections using the World Energy Projection System (WEPS) model for release year.…
## 14 co2-emissions     State CO2 Emissions             EIA CO2 Emissions data
```
Let's take a closer look at the Electricity directory.


```r
eia_dir("electricity")
```

```
## # A tibble: 6 × 3
##   id                              name                                                                       description                                      
##   <chr>                           <chr>                                                                      <chr>                                            
## 1 retail-sales                    Electricity Sales to Ultimate Customers                                    "Electricity sales to ultimate customer by state…
## 2 electric-power-operational-data Electric Power Operations (Annual and Monthly)                             "Monthly and annual electric power operations by…
## 3 rto                             Electric Power Operations (Daily and Hourly)                               "Hourly and daily electric power operations by b…
## 4 state-electricity-profiles      State Specific Data                                                        "State Specific Data"                            
## 5 operating-generator-capacity    Inventory of Operable Generators                                           "Inventory of operable generators in the U.S.\n …
## 6 facility-fuel                   Electric Power Operations for Individual Power Plants (Annual and Monthly) "Annual and monthly electric power operations fo…
```

There are six sub-folders within the electricity directory.
Using Retail Sales as an example, let's see what sub-folders are available there.


```r
eia_dir("electricity/retail-sales")
```

```
## No further sub-directories to discover.
## Use `eia_metadata("electricity/retail-sales")` to explore this data.
```

At this point, we've been informed that we've reached the end of the directory path;
i.e. the terminal directory within which there are data to be had. To better understand
what data is available here and how it can be obtained, we have been prompted to use
`eia::eia_metadata("electricity/retail-sales")`.


```r
eia::eia_metadata("electricity/retail-sales")
```

```
## $Name
## [1] "Electricity Sales to Ultimate Customers"
## 
## $Description
## [1] "Electricity sales to ultimate customer by state and sector (number of customers, average price, revenue, and megawatthours of sales).  \n    Sources: Forms EIA-826, EIA-861, EIA-861M"
## 
## $Data
## # A tibble: 4 × 3
##   id        alias                                              units                 
##   <chr>     <chr>                                              <chr>                 
## 1 revenue   Revenue from Sales to Ultimate Customers           million dollars       
## 2 sales     Megawatthours Sold to Utlimate Customers           million kilowatthours 
## 3 price     Average Price of Electricity to Utlimate Customers cents per kilowatthour
## 4 customers Number of Ultimate Customers                       number of customers   
## 
## $Facets
## # A tibble: 2 × 2
##   id       description          
##   <chr>    <chr>                
## 1 stateid  State / Census Region
## 2 sectorid Sector               
## 
## $Frequency
## # A tibble: 3 × 4
##   id        description                            query format 
##   <chr>     <chr>                                  <chr> <chr>  
## 1 monthly   One data point for each month.         M     YYYY-MM
## 2 quarterly One data point every 3 months.         Q     YYYY-QQ
## 3 annual    One data point for each calendar year. A     YYYY   
## 
## $Defaults
## # A tibble: 1 × 2
##   format  frequency
##   <chr>   <chr>    
## 1 YYYY-MM monthly  
## 
## $Period
## # A tibble: 1 × 2
##   start   end    
##   <chr>   <chr>  
## 1 2001-01 2023-07
```

The console output of `eia_metadata()`, above, provides a brief description, available data
values (data column names), facet ids for filtering, available time frequencies, a
set of default values for formats and frequency, and finally the full time range
of available data.

### Data Values

"Data Values" are just the names of the columns that hold the specific, respective data value.
In this example, we are interested in the overall number of power sold to customers.
The associated column name for this is `"sales"`.

### Facet filtering

But what if we only want `"sales"` for residential customers in Vermont?
This is where `facets` come in, and we can obtain specific values for facets by
way of `eia_facets`.

Remember, `eia_metadata()` provided us with the facet ids (`"stateid"`, `"sectorid"`)
needed to obtain the facet values.


```r
# State / Region
eia_facets("electricity/retail-sales", "stateid")
```

```
## # A tibble: 62 × 3
##    id    name               alias                           
##    <chr> <chr>              <chr>                           
##  1 MA    Massachusetts      (MA) Massachusetts              
##  2 VT    Vermont            (VT) Vermont                    
##  3 WA    Washington         (WA) Washington                 
##  4 ENC   East North Central Region: (ENC) East North Central
##  5 WNC   West North Central Region: (WNC) West North Central
##  6 NC    North Carolina     (NC) North Carolina             
##  7 HI    Hawaii             (HI) Hawaii                     
##  8 MD    Maryland           (MD) Maryland                   
##  9 NM    New Mexico         (NM) New Mexico                 
## 10 MTN   Mountain           Region: (MTN) Mountain          
## # … with 52 more rows
```

```r
# Sector
eia_facets("electricity/retail-sales", "sectorid")
```

```
## # A tibble: 6 × 3
##   id    name           alias               
##   <chr> <chr>          <chr>               
## 1 COM   commercial     (COM) commercial    
## 2 RES   residential    (RES) residential   
## 3 ALL   all sectors    (ALL) all sectors   
## 4 OTH   other          (OTH) other         
## 5 TRA   transportation (TRA) transportation
## 6 IND   industrial     (IND) industrial
```

The above output provides the ids for both the State/Region and Sector that will
be required for obtaining Retail Sales for Residential customers in Vermont.

  * `"stateid"` for Vermont is "VT"
  * `"sectorid"` for residential is "RES"

## Getting data

### Data values and facet subsetting

From the Data Values (column names) and Facet IDs obtained above, we can now
effectively create a query with `eia_data()` to get just that.

Note that the `facets` argument requires a named list with the proper facet IDs
discovered above.


```r
eia_data(
  dir = "electricity/retail-sales",
  data = "sales",
  facets = list(stateid = "OH", sectorid = "RES")
)
```

```
## # A tibble: 271 × 7
##    period  stateid stateDescription sectorid sectorName  sales `sales-units`        
##    <chr>   <chr>   <chr>            <chr>    <chr>       <dbl> <chr>                
##  1 2016-05 OH      Ohio             RES      residential 3374. million kilowatthours
##  2 2013-11 OH      Ohio             RES      residential 4032. million kilowatthours
##  3 2023-03 OH      Ohio             RES      residential 4347. million kilowatthours
##  4 2013-12 OH      Ohio             RES      residential 5201. million kilowatthours
##  5 2017-03 OH      Ohio             RES      residential 4118. million kilowatthours
##  6 2016-11 OH      Ohio             RES      residential 3471. million kilowatthours
##  7 2015-09 OH      Ohio             RES      residential 4148. million kilowatthours
##  8 2013-07 OH      Ohio             RES      residential 5117. million kilowatthours
##  9 2019-07 OH      Ohio             RES      residential 5804. million kilowatthours
## 10 2019-04 OH      Ohio             RES      residential 3263. million kilowatthours
## # … with 261 more rows
```

But what if we want both sales and price?
Further, what if we also want multiple sectors, say, residential and commercial?
We can simply concatenate these entries with `c()`


```r
(d <- eia_data(
  dir = "electricity/retail-sales",
  data = c("sales", "price"),
  facets = list(stateid = "OH", sectorid = c("RES", "COM"))
))
```

```
## # A tibble: 542 × 9
##    period  stateid stateDescription sectorid sectorName  sales price `sales-units`         `price-units`         
##    <chr>   <chr>   <chr>            <chr>    <chr>       <dbl> <dbl> <chr>                 <chr>                 
##  1 2016-05 OH      Ohio             COM      commercial  3900. 10    million kilowatthours cents per kilowatthour
##  2 2016-05 OH      Ohio             RES      residential 3374. 13.2  million kilowatthours cents per kilowatthour
##  3 2013-11 OH      Ohio             COM      commercial  3638.  9.32 million kilowatthours cents per kilowatthour
##  4 2013-11 OH      Ohio             RES      residential 4032. 12.0  million kilowatthours cents per kilowatthour
##  5 2023-03 OH      Ohio             COM      commercial  3868. 10.4  million kilowatthours cents per kilowatthour
##  6 2023-03 OH      Ohio             RES      residential 4347. 14.9  million kilowatthours cents per kilowatthour
##  7 2013-12 OH      Ohio             COM      commercial  3823.  9.06 million kilowatthours cents per kilowatthour
##  8 2013-12 OH      Ohio             RES      residential 5201. 11.3  million kilowatthours cents per kilowatthour
##  9 2017-03 OH      Ohio             COM      commercial  3857. 10.2  million kilowatthours cents per kilowatthour
## 10 2017-03 OH      Ohio             RES      residential 4118. 12.6  million kilowatthours cents per kilowatthour
## # … with 532 more rows
```

### Frequency, time subsetting, and sorting

This electric retail sales data is available in multiple frequencies and
for a defined date range, as shown below:


```
## Frequency:
```

```
##          id                            description query  format
## 1   monthly         One data point for each month.     M YYYY-MM
## 2 quarterly         One data point every 3 months.     Q YYYY-QQ
## 3    annual One data point for each calendar year.     A    YYYY
```

```
## 
## Date Range:
##    2001-01 to 2023-07
```

The default frequency for this data is monthly, but maybe we only want annualized
data for a truncated time frame, say the last five years. We can do that with the
`start`, `end`, and `freq` arguments of `eia_data()`.


```r
eia_data(
  dir = "electricity/retail-sales",
  data = c("sales", "price"),
  facets = list(stateid = "OH", sectorid = c("RES", "COM")),
  freq = "annual",
  start = "2013",
  end = "2023"
)
```

```
## # A tibble: 20 × 9
##    period stateid stateDescription sectorid sectorName   sales price `sales-units`         `price-units`         
##     <int> <chr>   <chr>            <chr>    <chr>        <dbl> <dbl> <chr>                 <chr>                 
##  1   2016 OH      Ohio             COM      commercial  47742.  9.97 million kilowatthours cents per kilowatthour
##  2   2016 OH      Ohio             RES      residential 52524. 12.5  million kilowatthours cents per kilowatthour
##  3   2019 OH      Ohio             COM      commercial  46009.  9.72 million kilowatthours cents per kilowatthour
##  4   2019 OH      Ohio             RES      residential 52226. 12.4  million kilowatthours cents per kilowatthour
##  5   2015 OH      Ohio             COM      commercial  47124. 10.1  million kilowatthours cents per kilowatthour
##  6   2015 OH      Ohio             RES      residential 51493. 12.8  million kilowatthours cents per kilowatthour
##  7   2021 OH      Ohio             COM      commercial  44980.  9.75 million kilowatthours cents per kilowatthour
##  8   2021 OH      Ohio             RES      residential 53171. 12.8  million kilowatthours cents per kilowatthour
##  9   2022 OH      Ohio             COM      commercial  46009. 10.5  million kilowatthours cents per kilowatthour
## 10   2022 OH      Ohio             RES      residential 53515. 14.0  million kilowatthours cents per kilowatthour
## 11   2018 OH      Ohio             COM      commercial  47192. 10.1  million kilowatthours cents per kilowatthour
## 12   2018 OH      Ohio             RES      residential 54452. 12.6  million kilowatthours cents per kilowatthour
## 13   2014 OH      Ohio             RES      residential 52804. 12.5  million kilowatthours cents per kilowatthour
## 14   2014 OH      Ohio             COM      commercial  47005.  9.83 million kilowatthours cents per kilowatthour
## 15   2017 OH      Ohio             COM      commercial  46158. 10.0  million kilowatthours cents per kilowatthour
## 16   2017 OH      Ohio             RES      residential 49796. 12.6  million kilowatthours cents per kilowatthour
## 17   2020 OH      Ohio             COM      commercial  43204.  9.53 million kilowatthours cents per kilowatthour
## 18   2020 OH      Ohio             RES      residential 52553. 12.3  million kilowatthours cents per kilowatthour
## 19   2013 OH      Ohio             COM      commercial  46718.  9.35 million kilowatthours cents per kilowatthour
## 20   2013 OH      Ohio             RES      residential 52158. 12.0  million kilowatthours cents per kilowatthour
```

As you can see, we get back a data frame with 10 annual observations, two for
each sector (residential and commercial). However, you may have also noticed the
hectic ordering of the returned data. Thankfully, we can have the API service sort
this in either ascending or descending order using the `sort` function argument.

Similar to `facets`, `sort` requires a named list object with two components:

  * `"cols"` will contain a list of column names by which to order.
  * `"ordr"` requires a single character, the value of which can be either "asc" or "desc"
  for ascending and descending, respectively.


```r
eia_data(
  dir = "electricity/retail-sales",
  data = c("sales", "price"),
  facets = list(stateid = "OH", sectorid = c("RES", "COM")),
  freq = "annual",
  start = "2013",
  end = "2023",
  sort = list(cols = c("period", "sectorid"), ordr = "asc")
)
```

```
## # A tibble: 20 × 9
##    period stateid stateDescription sectorid sectorName   sales price `sales-units`         `price-units`         
##     <int> <chr>   <chr>            <chr>    <chr>        <dbl> <dbl> <chr>                 <chr>                 
##  1   2013 OH      Ohio             COM      commercial  46718.  9.35 million kilowatthours cents per kilowatthour
##  2   2013 OH      Ohio             RES      residential 52158. 12.0  million kilowatthours cents per kilowatthour
##  3   2014 OH      Ohio             COM      commercial  47005.  9.83 million kilowatthours cents per kilowatthour
##  4   2014 OH      Ohio             RES      residential 52804. 12.5  million kilowatthours cents per kilowatthour
##  5   2015 OH      Ohio             COM      commercial  47124. 10.1  million kilowatthours cents per kilowatthour
##  6   2015 OH      Ohio             RES      residential 51493. 12.8  million kilowatthours cents per kilowatthour
##  7   2016 OH      Ohio             COM      commercial  47742.  9.97 million kilowatthours cents per kilowatthour
##  8   2016 OH      Ohio             RES      residential 52524. 12.5  million kilowatthours cents per kilowatthour
##  9   2017 OH      Ohio             COM      commercial  46158. 10.0  million kilowatthours cents per kilowatthour
## 10   2017 OH      Ohio             RES      residential 49796. 12.6  million kilowatthours cents per kilowatthour
## 11   2018 OH      Ohio             COM      commercial  47192. 10.1  million kilowatthours cents per kilowatthour
## 12   2018 OH      Ohio             RES      residential 54452. 12.6  million kilowatthours cents per kilowatthour
## 13   2019 OH      Ohio             COM      commercial  46009.  9.72 million kilowatthours cents per kilowatthour
## 14   2019 OH      Ohio             RES      residential 52226. 12.4  million kilowatthours cents per kilowatthour
## 15   2020 OH      Ohio             COM      commercial  43204.  9.53 million kilowatthours cents per kilowatthour
## 16   2020 OH      Ohio             RES      residential 52553. 12.3  million kilowatthours cents per kilowatthour
## 17   2021 OH      Ohio             COM      commercial  44980.  9.75 million kilowatthours cents per kilowatthour
## 18   2021 OH      Ohio             RES      residential 53171. 12.8  million kilowatthours cents per kilowatthour
## 19   2022 OH      Ohio             COM      commercial  46009. 10.5  million kilowatthours cents per kilowatthour
## 20   2022 OH      Ohio             RES      residential 53515. 14.0  million kilowatthours cents per kilowatthour
```
